version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5673:5672"
    environment:
      RABBITMQ_DEFAULT_USER: xyh123
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq

volumes:
  rabbitmq-home:

